Abhinandan-Kushwaha/react-native-gifted-charts

- src/PieChart/main.tsx
Hi!
I'm using the lib in a react-native-web app, on mobile it's no problem, but on the web I got this error when using piechart.
Uncaught ReferenceError: Unable to access 'total' before initialization in main.tsx:142.
I solved it by just declaring above, it worked on both platforms.
Thank you and congratulations for the project!
> Fix uninitialized total variable when using in web

- src/PieChart/main.tsx
Hello
While using this lib in my react-native project, I noticed a recurring error on using `showText` prop on the `PieChart` component.
I looked up the source code and spotted a missing unique key prop while mapping and rendering each pie elements.
The `SvgText` component is missing a key prop as being extracted from the mapped data, so I'm contributing to fix this issue.
Thank you for the project and taking time to review my pull request.
> Fix missing unique key prop

- src/Components/BarAndLineChartsWrapper/renderHorizSections.tsx
This is a fix for the issue discussed in: https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/issues/364.
It should be possible to set `yAxisLabelTexts` to e.g `['-60.0', '-45.0', '-30.0', '-15.0', '0.0', '15.0', '30.0', '45.0', '60.0']` and have the correct labels rendered on the y-axis. Maybe it should be added to the documentation how to enter yAxisLabelTexts including negative values?
I'm not sure how this will work together with the newly added `secondaryYAxis`.
> Fix labels in bar/line-chart y-axis with negative values

- src/Components/BarAndLineChartsWrapper/index.tsx
- src/utils/types.ts
I keep getting the log: 
'You specified onScroll on a but not scrollEventThrottle. You will only receive one event. Using 16 you get all the events but be aware that it may cause frame drops, use a bigger number if you don't need as much precision.'
> fix: exposed the scrollEventThrottle as a prop

- src/PieChart/index.tsx
Posted this issue the other day : https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/issues/428
It was pretty annoying and by continuing my development, I found an other small issue about the focused thing on the pie chart. 
I used a useEffect so each time a re-render was needed, it would check again some stuff to re-render correctly the chart and the focused part. 
I put comment in the code too, just to help explain what I did. Maybe it's overkill. You can delete them if you want 😁 
Let me know if you have any questions.
> fix/Pie Chart focus update 

- src/BarChart/RenderStackBars.tsx
- src/BarChart/index.tsx
- src/Components/BarAndLineChartsWrapper/index.tsx
A mix of _positive_ and _negative_ values in the stacked bar chart put the whole bar below the x-axis.
This PR allows a stacked bar chart to have _positive_ and _negative_ values in the same stack and renders it correctly.
With this stack data
```typescript
const stacks: stackItemType[] = [
{
// Mix of positive and negative values
label: 'Nov "23',
stacks: [
{
value: 20,
color: '#35aa0a',
},
{
value: -5,
color: '#ffa600',
},
{
value: -6,
color: '#dc25bb',
},
{
value: 10,
color: '#003f5c',
},
],
},
// Only positive values
{
label: 'Dez "23',
stacks: [
{
value: 8,
color: '#35aa0a',
},
{
value: 1,
color: '#ffa600',
},
{
value: 7,
color: '#dc25bb',
},
],
},
// Only negative values
{
label: 'Dez "23',
stacks: [
{
value: -5,
color: '#35aa0a',
},
{
value: 0,
color: '#ffa600',
},
{
value: -3, …
```
> Fix: Bar chart -> Support mix of positive + negative values

- src/PieChart/index.tsx
Hi Abhinandan,
I wanted to bring to your attention a minor issue I encountered when using a PieChart with the `semiCircle` option set to `true`. Currently, it seems that the height of the semicircular pie chart is calculated as if it were a full pie chart, which can lead to suboptimal visualization. This is what I mean:
I've identified a simple fix and have submitted this Pull Request to address the issue. This is the result:
Thank you.
Mauro
> Fix height for PieChart with semiCircle

- src/LineChart/index.tsx
Simple changes to fix data issues with linecharts. These would cause the data to use incorrect prop data eg. data3 used data2 prop. Also, some of the other data seemed incorrect when reading the code in similar statements above.
> Bug Fix: LineChart data amendments

- CONTRIBUTING.md
- package.json
1. Ensures that `gifted-charts-core` is downloaded.
2. Ensures contributors don't need to modify the dependency list to contribute
> fix: update dependency list

- src/PieChart/index.tsx
I noticed that the shiftTextX and shiftTextY props were missing in the sectionAutoFocus scenario for the PieChart component. 
This caused a change in text location when focused, especially when the radius was conditionally changed. 
Despite passing values for shiftTextX and shiftTextY, they were not being applied.
To fix this issue, I added and passed the props values of shiftTextX and shiftTextY, which were previously missing.
This ensured that the text location remained consistent with user defined values even when the chart was focused and the radius was dynamically adjusted.
> added shiftTextX and shiftTextY for sectionAutoFocus scenario of PieChart

- src/PieChart/index.tsx
Updated PieChart to pass the innerCircleBorderWidth to all instances of renderInnerCircle(. Current implementation is passing 0 when using (innerRadius-inwardExtraLengthForFocus) which was causing the border to not appear.
It may be that the second renderInnerCircle should be 0, but in that case it might need to be a conditional render if inwardExtraLengthForFocus exists/!=0, because currently it seems to override any innerCircleBorderWidth I provide to 0.
> Fix - PieChart innerCircleBorderWidth

- src/PieChart/index.tsx
Related to https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/issues/564
The `PieChart` on Android didn't call `onPress` when providing the prop `focusOnPress` or `sectionAutoFocus`.
Probably because the focused/bigger PieChart was covering the main pie chart.
This change fixes this for me and onPress will be called on iOS + Android.
Please test before merging :)
> fix: PieChart: Make paths pressable on Android

- src/index.tsx
exporting the DataSet type helps allows proper typing of data being used to created charts using the `dataSet` prop.
> Export DataSet type

- package.json
- src/BarChart/RenderBars.tsx
- src/BarChart/index.tsx
- src/Components/BarAndLineChartsWrapper/renderLineInBarChart/index.tsx
- src/Components/BarAndLineChartsWrapper/renderLineInBarChart/renderDataPoints.tsx
- src/Components/BarAndLineChartsWrapper/renderLineInBarChart/renderSpecificDataPoints.tsx
- src/Components/BarAndLineChartsWrapper/renderLineInBarChart/renderSpecificVerticalLines.tsx
- src/Components/BarAndLineChartsWrapper/renderVerticalLines.tsx
- src/Components/BarSpecificComponents/barBackgroundPattern.tsx
- src/Components/BarSpecificComponents/cap.tsx
- src/Components/common/LinearGradient.tsx
- src/Components/common/Pointer.tsx
- src/Components/common/StripAndLabel.tsx
- src/LineChart/LineChartBicolor.tsx
- src/LineChart/index.tsx
- src/PieChart/index.tsx
After using this library, our project is failing because if the type errors in this library. This PR fixes all the errors, generally just by adding type `any` (or type `number` where it's obviously a number).
> Fix: remove all type errors

- src/LineChart/index.tsx
Hi @Abhinandan-Kushwaha, 
to continue this [PR](https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/pull/644)
At initialData = props.dataSet?.[0]?.data ?? props.data ?? [];
with initialData result
[{ "dataPointLabelComponent": [Function anonymous], "dataPointLabelShiftX": 75, "focusedDataPointColor": "rgba(60, 121, 245, 1)", "focusedDataPointRadius": 4, "label": "4", "value": 70.88 }, { "label": "5", "value": null }, { "dataPointLabelComponent": [Function anonymous], "dataPointLabelShiftX": 75, "focusedDataPointColor": "rgba(60, 121, 245, 1)", "focusedDataPointRadius": 4, "label": "6", "value": 70.88 }, { "dataPointLabelComponent": [Function anonymous], "dataPointLabelShiftX": 75, "focusedDataPointColor": "rgba(60, 121, 245, 1)", "focusedDataPointRadius": 4, "label": "7", …
> Fix crash Error: AnimatedValue: Attempting to set value to undefined

- src/BarChart/RenderStackBars.tsx
This PR depends on https://github.com/Abhinandan-Kushwaha/gifted-charts-core/pull/36
Follows the established pattern for bar charts to allow customizing label width on stacked bar charts.
This is needed to fix my stacked bar chart, where two stacked bars are close together under one label:
Labels with `labelWidth` look like this:
> Add labelWidth prop to stacked bar charts

- src/Components/BarAndLineChartsWrapper/index.tsx
Setting scrollAnimation to false in a LineChart does not disable the initial animation for scrollToIndex. I am passing scrollAnimation to `scrollRef.current.scrollTo` so the scrollAnimation is applied for `scrollToIndex`.
Issue: https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/issues/859
> Use scrollAnimation when scrolling to index

- src/Components/BarSpecificComponents/tooltip.tsx
Resolves #913 
For small tooltips shift value is negative and according to the calculations for `left` property its absolute value will be added to `leftSpacing` value resulting in correct tooltip position
> Fix `autoCenterTooltip` property behavior for small tooltips

- src/Components/common/StripAndLabel.tsx
Closes: https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/issues/952
This is already working with datapoints contained within the screenWidth, but if I press datapoints beyond the screenWidth, the strip is not displayed.
Use totalWidth instead of screenWidth in the Strip container.
https://github.com/user-attachments/assets/b34f9625-2d97-40fe-95d9-67286284b6b8
https://github.com/user-attachments/assets/eb8e8e38-8b0c-4497-aa97-477e9ee19c96
> LineChart - Use totalWidth to show strips beyond the screenWidth

- src/PieChart/main.tsx
Implementing the already existing props `pieInnerComponentHeight` and `pieInnerComponentWidth` so that `localPieInnerComponent` can be centered.
> adding support for pie inner component offset

- docs/BarChart/BarChartProps.md
- src/BarChart/RenderBars.tsx
- src/BarChart/index.tsx
- src/Components/BarAndLineChartsWrapper/renderLineInBarChart/index.tsx
- make `selectedIndex` an array
- `highlightedBarIndex` can now be an `number[]` or number
Steps to verify
1. Follow example from https://gifted-charts.web.app/barchart/#customised
2. Now pass `highlightedBarIndex={[2,3]}` and `highlightEnabled` prop to `<BarChart />`
3. This should now highlight bars at index 2 and 3
Notes:
- This multiple indices is only limited for BarChart and not others
- Existing workflow should not be affected, since we're also supporting `highlightedBarIndex` and `focusedBarIndex` to be a regular number
Closes: https://github.com/Abhinandan-Kushwaha/react-native-gifted-charts/issues/1083
> feat: implementation for highlighted/focused mutiple indicies

- src/BarChart/RenderStackBars.tsx
Currently a pattern on a bar **doesn't cover the whole** bar.
It leads to a 1px margin to the **top** and to the **left**. 
This PR removed that unwanted margin.
Code for screenshots below:
```typescript
const data: stackDataItem[] = [
{
barBackgroundPattern: DiagonalLinePattern,
patternId: 'DiagonalLines',
stacks: [
{
value: 110,
color: '#ff000d', // red
},
],
},
];
<BarChart stackData={data} barWidth={40} spacing={30} />
```
**Before** with red line (visible red bar) visible behind the pattern
**After** without red line visible
> fix: Remove background pattern margin

- examples/RadarChart/MultipleLineLabel.tsx
- examples/index.tsx
- src/RadarChart/index.tsx
Issue:
The RadarChart component provided by react-native-gifted-charts renders labels using svg text. However, when label text is too long, line breaks are not supported, which reduces readability.
Solution:
We modified the rendering logic so that the label string is split by the \n character and each part is wrapped in a <TSpan> element. This enables proper line breaks for long label texts, resulting in clearer and more readable labels.
> fix: support multiline RadarChart labels using <TSpan>
